version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: itez_frontend
    container_name: itez-frontend
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - ITEZ_API_URI=http://localhost:8000/api
    command: npm run dev
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"
