export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOADED = "AUTH_LOADED";
export const RESET_USER_REGISTER_SUCCESS = "RESET_USER_REGISTER_SUCCESS";

// Beneficairy Types
export const BENEFICIARY_CREATE_SUCCESS = "BENEFICIARY_CREATE_SUCCESS";
export const BENEFICIARY_CREATE_FAILURE = "BENEFICIARY_CREATE_FAILURE";
export const BENEFICIARY_UPDATE_SUCCESS = "BENEFICIARY_UPDATE_SUCCESS";
export const BENEFICIARY_UPDATE_FAILURE = "BENEFICIARY_UPDATE_FAILURE";
export const GET_ALL_BENEFICIARIES = "GET_ALL_BENEFICIARIES";
export const GET_BENEFICIARY_BY_ID = "GET_BENEFICIARY_BY_ID";

// Agent Types
export const AGENT_CREATE_SUCCESS = "AGENT_CREATE_SUCCESS";
export const AGENT_CREATE_FAILURE = "AGENT_CREATE_FAILURE";
export const AGENT_UPDATE_SUCCESS = "AGENT_UPDATE_SUCCESS";
export const AGENT_UPDATE_FAILURE = "AGENT_UPDATE_FAILURE";
export const GET_ALL_AGENTS = "GET_ALL_AGENTS";
export const GET_AGENT_BY_ID = "GET_AGENT_BY_ID";

// Work Details
export const WORK_DETAILS_CREATE_SUCCESS = "WORK_DETAILS_CREATE_SUCCESS";
export const WORK_DETAILS_CREATE_FAILURE = "WORK_DETAILS_CREATE_FAILURE";
export const WORK_DETAILS_UPDATE_SUCCESS = "WORK_DETAILS_UPDATE_SUCCESS";
export const WORK_DETAILS_UPDATE_FAILURE = "WORK_DETAILS_UPDATE_FAILURE";
export const GET_ALL_WORK_DETAILS = "GET_ALL_WORK_DETAILS";
export const GET_WORK_DETAILS_BY_ID = "GET_WORK_DETAILS_BY_ID";

//Location Types
